# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'untitled.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
import images


class Ui_QuickLaunchPanelsWindow(object):
    def setupUi(self, QuickLaunchPanelsWindow):
        QuickLaunchPanelsWindow.setObjectName("QuickLaunchPanelsWindow")
        QuickLaunchPanelsWindow.resize(250, 230)
        self.centralwidget = QtWidgets.QWidget(QuickLaunchPanelsWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.centralwidget.setStyleSheet("background: #222; color: #aaa;")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.verticalLayout.setContentsMargins(10, 0, 10, 0)

        self.lv = QtWidgets.QListView(QuickLaunchPanelsWindow)        
        self.lv.setObjectName("lv")
        self.lv.setSizePolicy(self.sizePolicy())


        self.verticalLayout.addWidget(self.lv)
        
        self.bw = QtWidgets.QWidget(self.centralwidget)
        self.bw.setSizePolicy(self.sizePolicy(vexp = False))
        self.bw.setObjectName("bw")
        self.bw.setMaximumSize(QtCore.QSize(500, 50))
        
        self.verticalLayout.addWidget(self.bw)

        self.horizontalLayout = QtWidgets.QHBoxLayout(self.bw)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")        
        
        self.bAdd = self.newButton("bAdd","add.png")
        self.horizontalLayout.addWidget(self.bAdd)
        self.bEdit = self.newButton("bEdit","edit.png")
        self.horizontalLayout.addWidget(self.bEdit)
        self.bDel = self.newButton("bDel","delete.png")
        self.horizontalLayout.addWidget(self.bDel)        
        
        
        QuickLaunchPanelsWindow.setCentralWidget(self.centralwidget)        
        self.retranslateUi(QuickLaunchPanelsWindow)
        QtCore.QMetaObject.connectSlotsByName(QuickLaunchPanelsWindow)
        
        
    def newButton(self,name,iconname):
        btn = QtWidgets.QToolButton(self.bw)
        btn.setMinimumSize(QtCore.QSize(34, 34))
        btn.setIconSize(QtCore.QSize(24,24))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/"+iconname), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        btn.setIcon(icon)
        btn.setObjectName(name)
        return btn
    
    def sizePolicy(self,hexp=True,vexp=True):
        if hexp:
            hpol = QtWidgets.QSizePolicy.Expanding
        else:
            hpol = QtWidgets.QSizePolicy.Preferred
        if vexp:
            vpol = QtWidgets.QSizePolicy.Expanding
        else:
            vpol = QtWidgets.QSizePolicy.Preferred
        sizePolicy = QtWidgets.QSizePolicy(hpol, vpol)
        if hpol: sizePolicy.setHorizontalStretch(1)
        if vpol: sizePolicy.setVerticalStretch(1)
        return sizePolicy

    def retranslateUi(self, QuickLaunchPanelsWindow):
        _translate = QtCore.QCoreApplication.translate
        QuickLaunchPanelsWindow.setWindowTitle(_translate("QuickLaunchPanelsWindow", "Панели быстрого запуска приложений"))

