# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'settingsdialogwindow.ui'
#
# Created by: PyQt5 UI code generator 5.14.1
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(559, 411)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(Dialog.sizePolicy().hasHeightForWidth())
        Dialog.setSizePolicy(sizePolicy)
        self.mainLayout = QtWidgets.QVBoxLayout(Dialog)
        self.mainLayout.setContentsMargins(2, 2, 2, 2)
        self.mainLayout.setSpacing(0)
        self.mainLayout.setObjectName("mainLayout")
        self.mainHorLayout = QtWidgets.QHBoxLayout()
        self.mainHorLayout.setObjectName("mainHorLayout")
        self.lv = QtWidgets.QListView(Dialog)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lv.sizePolicy().hasHeightForWidth())
        self.lv.setSizePolicy(sizePolicy)
        self.lv.setMaximumSize(QtCore.QSize(200, 16777215))
        self.lv.setContextMenuPolicy(QtCore.Qt.CustomContextMenu)
        self.lv.setObjectName("lv")
        self.mainHorLayout.addWidget(self.lv)
        self.stackedWidget = QtWidgets.QStackedWidget(Dialog)
        self.stackedWidget.setObjectName("stackedWidget")
        self.page_1 = QtWidgets.QWidget()
        self.page_1.setObjectName("page_1")
        self.label = QtWidgets.QLabel(self.page_1)
        self.label.setGeometry(QtCore.QRect(10, 20, 201, 16))
        self.label.setObjectName("label")
        self.sbDefaultIconSize = QtWidgets.QSpinBox(self.page_1)
        self.sbDefaultIconSize.setGeometry(QtCore.QRect(220, 16, 51, 26))
        self.sbDefaultIconSize.setMinimum(16)
        self.sbDefaultIconSize.setMaximum(256)
        self.sbDefaultIconSize.setSingleStep(8)
        self.sbDefaultIconSize.setProperty("value", 48)
        self.sbDefaultIconSize.setObjectName("sbDefaultIconSize")
        self.label_2 = QtWidgets.QLabel(self.page_1)
        self.label_2.setGeometry(QtCore.QRect(10, 54, 201, 16))
        self.label_2.setObjectName("label_2")
        self.sbIconSize = QtWidgets.QSpinBox(self.page_1)
        self.sbIconSize.setGeometry(QtCore.QRect(220, 50, 51, 26))
        self.sbIconSize.setMinimum(16)
        self.sbIconSize.setMaximum(256)
        self.sbIconSize.setSingleStep(8)
        self.sbIconSize.setProperty("value", 32)
        self.sbIconSize.setObjectName("sbIconSize")
        self.sbScaledIconSize = QtWidgets.QSpinBox(self.page_1)
        self.sbScaledIconSize.setGeometry(QtCore.QRect(220, 86, 51, 26))
        self.sbScaledIconSize.setMinimum(16)
        self.sbScaledIconSize.setMaximum(256)
        self.sbScaledIconSize.setSingleStep(8)
        self.sbScaledIconSize.setProperty("value", 48)
        self.sbScaledIconSize.setObjectName("sbScaledIconSize")
        self.label_3 = QtWidgets.QLabel(self.page_1)
        self.label_3.setGeometry(QtCore.QRect(10, 90, 201, 16))
        self.label_3.setObjectName("label_3")
        self.cbWithText = QtWidgets.QCheckBox(self.page_1)
        self.cbWithText.setGeometry(QtCore.QRect(10, 120, 171, 21))
        self.cbWithText.setObjectName("cbWithText")
        self.cbShaddow = QtWidgets.QCheckBox(self.page_1)
        self.cbShaddow.setGeometry(QtCore.QRect(10, 145, 131, 21))
        self.cbShaddow.setObjectName("cbShaddow")
        self.bShaddowColor = QtWidgets.QPushButton(self.page_1)
        self.bShaddowColor.setGeometry(QtCore.QRect(34, 170, 90, 28))
        self.bShaddowColor.setObjectName("bShaddowColor")
        self.lShaddowColor = QtWidgets.QLabel(self.page_1)
        self.lShaddowColor.setGeometry(QtCore.QRect(130, 173, 21, 21))
        self.lShaddowColor.setStyleSheet("background: #80000000;")
        self.lShaddowColor.setText("")
        self.lShaddowColor.setObjectName("lShaddowColor")
        self.label_7 = QtWidgets.QLabel(self.page_1)
        self.label_7.setGeometry(QtCore.QRect(40, 210, 101, 16))
        self.label_7.setObjectName("label_7")
        self.dsbShaddowOffsetX = QtWidgets.QDoubleSpinBox(self.page_1)
        self.dsbShaddowOffsetX.setGeometry(QtCore.QRect(140, 206, 71, 26))
        self.dsbShaddowOffsetX.setDecimals(1)
        self.dsbShaddowOffsetX.setMinimum(0.0)
        self.dsbShaddowOffsetX.setMaximum(8.0)
        self.dsbShaddowOffsetX.setSingleStep(0.1)
        self.dsbShaddowOffsetX.setProperty("value", 2.0)
        self.dsbShaddowOffsetX.setObjectName("dsbShaddowOffsetX")
        self.label_8 = QtWidgets.QLabel(self.page_1)
        self.label_8.setGeometry(QtCore.QRect(40, 236, 101, 16))
        self.label_8.setObjectName("label_8")
        self.dsbShaddowGause = QtWidgets.QDoubleSpinBox(self.page_1)
        self.dsbShaddowGause.setGeometry(QtCore.QRect(140, 232, 71, 26))
        self.dsbShaddowGause.setDecimals(1)
        self.dsbShaddowGause.setMinimum(0.0)
        self.dsbShaddowGause.setMaximum(16.0)
        self.dsbShaddowGause.setSingleStep(1.0)
        self.dsbShaddowGause.setProperty("value", 6.0)
        self.dsbShaddowGause.setObjectName("dsbShaddowGause")
        self.bTextColor = QtWidgets.QPushButton(self.page_1)
        self.bTextColor.setGeometry(QtCore.QRect(10, 270, 151, 28))
        self.bTextColor.setObjectName("bTextColor")
        self.lTextColor = QtWidgets.QLabel(self.page_1)
        self.lTextColor.setGeometry(QtCore.QRect(167, 273, 21, 21))
        self.lTextColor.setStyleSheet("background: #fff;")
        self.lTextColor.setText("")
        self.lTextColor.setObjectName("lTextColor")
        self.stackedWidget.addWidget(self.page_1)
        self.page_2 = QtWidgets.QWidget()
        self.page_2.setObjectName("page_2")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.page_2)
        self.verticalLayout.setContentsMargins(6, 6, 6, 6)
        self.verticalLayout.setSpacing(3)
        self.verticalLayout.setObjectName("verticalLayout")
        self.widget_2 = QtWidgets.QWidget(self.page_2)
        self.widget_2.setObjectName("widget_2")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.widget_2)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.widget_3 = QtWidgets.QWidget(self.widget_2)
        self.widget_3.setObjectName("widget_3")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.widget_3)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.label_4 = QtWidgets.QLabel(self.widget_3)
        self.label_4.setObjectName("label_4")
        self.verticalLayout_2.addWidget(self.label_4)
        self.pEdit = QtWidgets.QPlainTextEdit(self.widget_3)
        self.pEdit.setObjectName("pEdit")
        self.verticalLayout_2.addWidget(self.pEdit)
        self.horizontalLayout_2.addWidget(self.widget_3)
        self.widget_4 = QtWidgets.QWidget(self.widget_2)
        self.widget_4.setObjectName("widget_4")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.widget_4)
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.label_5 = QtWidgets.QLabel(self.widget_4)
        self.label_5.setObjectName("label_5")
        self.verticalLayout_3.addWidget(self.label_5)
        self.centralwidget = QtWidgets.QWidget(self.widget_4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.centralwidget.sizePolicy().hasHeightForWidth())
        self.centralwidget.setSizePolicy(sizePolicy)
        self.centralwidget.setMinimumSize(QtCore.QSize(140, 0))
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout_3.addWidget(self.centralwidget)
        self.bUpdate = QtWidgets.QPushButton(self.widget_4)
        self.bUpdate.setObjectName("bUpdate")
        self.verticalLayout_3.addWidget(self.bUpdate)
        self.horizontalLayout_2.addWidget(self.widget_4)
        self.verticalLayout.addWidget(self.widget_2)
        self.widget_7 = QtWidgets.QWidget(self.page_2)
        self.widget_7.setObjectName("widget_7")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout(self.widget_7)
        self.horizontalLayout_6.setContentsMargins(5, 5, 5, 5)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.label_9 = QtWidgets.QLabel(self.widget_7)
        self.label_9.setObjectName("label_9")
        self.horizontalLayout_6.addWidget(self.label_9)
        self.eTitle = QtWidgets.QLineEdit(self.widget_7)
        self.eTitle.setObjectName("eTitle")
        self.horizontalLayout_6.addWidget(self.eTitle)
        self.verticalLayout.addWidget(self.widget_7)
        self.widget = QtWidgets.QWidget(self.page_2)
        self.widget.setObjectName("widget")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.widget)
        self.horizontalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.bTitleColor = QtWidgets.QPushButton(self.widget)
        self.bTitleColor.setMinimumSize(QtCore.QSize(140, 0))
        self.bTitleColor.setObjectName("bTitleColor")
        self.horizontalLayout_3.addWidget(self.bTitleColor)
        self.lTitleColor = QtWidgets.QLabel(self.widget)
        self.lTitleColor.setMinimumSize(QtCore.QSize(30, 0))
        self.lTitleColor.setStyleSheet("background: #fff;")
        self.lTitleColor.setText("")
        self.lTitleColor.setObjectName("lTitleColor")
        self.horizontalLayout_3.addWidget(self.lTitleColor)
        self.verticalLayout.addWidget(self.widget)
        self.widget_6 = QtWidgets.QWidget(self.page_2)
        self.widget_6.setObjectName("widget_6")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.widget_6)
        self.horizontalLayout_5.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.bMenuBgColor = QtWidgets.QPushButton(self.widget_6)
        self.bMenuBgColor.setMinimumSize(QtCore.QSize(140, 0))
        self.bMenuBgColor.setObjectName("bMenuBgColor")
        self.horizontalLayout_5.addWidget(self.bMenuBgColor)
        self.lMenuBgColor = QtWidgets.QLabel(self.widget_6)
        self.lMenuBgColor.setMinimumSize(QtCore.QSize(30, 0))
        self.lMenuBgColor.setStyleSheet("background: #444;")
        self.lMenuBgColor.setText("")
        self.lMenuBgColor.setObjectName("lMenuBgColor")
        self.horizontalLayout_5.addWidget(self.lMenuBgColor)
        self.verticalLayout.addWidget(self.widget_6)
        self.widget_5 = QtWidgets.QWidget(self.page_2)
        self.widget_5.setObjectName("widget_5")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.widget_5)
        self.horizontalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.bMenuColor = QtWidgets.QPushButton(self.widget_5)
        self.bMenuColor.setMinimumSize(QtCore.QSize(150, 0))
        self.bMenuColor.setObjectName("bMenuColor")
        self.horizontalLayout_4.addWidget(self.bMenuColor)
        self.lMenuColor = QtWidgets.QLabel(self.widget_5)
        self.lMenuColor.setMinimumSize(QtCore.QSize(30, 0))
        self.lMenuColor.setStyleSheet("background: #fff;")
        self.lMenuColor.setText("")
        self.lMenuColor.setObjectName("lMenuColor")
        self.horizontalLayout_4.addWidget(self.lMenuColor)
        self.verticalLayout.addWidget(self.widget_5)
        self.stackedWidget.addWidget(self.page_2)
        self.page_3 = QtWidgets.QWidget()
        self.page_3.setObjectName("page_3")
        self.lGroupTitleColor = QtWidgets.QLabel(self.page_3)
        self.lGroupTitleColor.setGeometry(QtCore.QRect(170, 39, 24, 24))
        self.lGroupTitleColor.setStyleSheet("background: #fff;")
        self.lGroupTitleColor.setText("")
        self.lGroupTitleColor.setObjectName("lGroupTitleColor")
        self.bGroupTitleBorderColor = QtWidgets.QPushButton(self.page_3)
        self.bGroupTitleBorderColor.setGeometry(QtCore.QRect(10, 103, 151, 28))
        self.bGroupTitleBorderColor.setObjectName("bGroupTitleBorderColor")
        self.bGroupTitleBgColor = QtWidgets.QPushButton(self.page_3)
        self.bGroupTitleBgColor.setGeometry(QtCore.QRect(10, 70, 151, 28))
        self.bGroupTitleBgColor.setObjectName("bGroupTitleBgColor")
        self.lGroupTitleBorderColor = QtWidgets.QLabel(self.page_3)
        self.lGroupTitleBorderColor.setGeometry(QtCore.QRect(170, 106, 24, 24))
        self.lGroupTitleBorderColor.setStyleSheet("background: #2000ffff;")
        self.lGroupTitleBorderColor.setText("")
        self.lGroupTitleBorderColor.setObjectName("lGroupTitleBorderColor")
        self.bGroupTitleColor = QtWidgets.QPushButton(self.page_3)
        self.bGroupTitleColor.setGeometry(QtCore.QRect(10, 36, 151, 28))
        self.bGroupTitleColor.setObjectName("bGroupTitleColor")
        self.lGroupTitleBgColor = QtWidgets.QLabel(self.page_3)
        self.lGroupTitleBgColor.setGeometry(QtCore.QRect(170, 73, 24, 24))
        self.lGroupTitleBgColor.setStyleSheet("background: #40000000;")
        self.lGroupTitleBgColor.setText("")
        self.lGroupTitleBgColor.setObjectName("lGroupTitleBgColor")
        self.label_6 = QtWidgets.QLabel(self.page_3)
        self.label_6.setGeometry(QtCore.QRect(10, 10, 141, 16))
        self.label_6.setObjectName("label_6")
        self.stackedWidget.addWidget(self.page_3)
        self.mainHorLayout.addWidget(self.stackedWidget)
        self.mainLayout.addLayout(self.mainHorLayout)
        self.buttonswidget = QtWidgets.QWidget(Dialog)
        self.buttonswidget.setMinimumSize(QtCore.QSize(0, 40))
        self.buttonswidget.setObjectName("buttonswidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.buttonswidget)
        self.horizontalLayout.setObjectName("horizontalLayout")
        spacerItem = QtWidgets.QSpacerItem(327, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.bOk = QtWidgets.QPushButton(self.buttonswidget)
        self.bOk.setObjectName("bOk")
        self.horizontalLayout.addWidget(self.bOk)
        self.bCancel = QtWidgets.QPushButton(self.buttonswidget)
        self.bCancel.setObjectName("bCancel")
        self.horizontalLayout.addWidget(self.bCancel)
        self.mainLayout.addWidget(self.buttonswidget)

        self.retranslateUi(Dialog)
        self.stackedWidget.setCurrentIndex(1)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.label.setText(_translate("Dialog", "Размер загружаемой иконки:"))
        self.label_2.setText(_translate("Dialog", "Размер отображаемой иконки:"))
        self.label_3.setText(_translate("Dialog", "Размер увеличенной иконки:"))
        self.cbWithText.setText(_translate("Dialog", "Вид иконок - список"))
        self.cbShaddow.setText(_translate("Dialog", "Тень иконок"))
        self.bShaddowColor.setText(_translate("Dialog", "Цвет тени:"))
        self.label_7.setText(_translate("Dialog", "Смещение:"))
        self.label_8.setText(_translate("Dialog", "Размытие:"))
        self.bTextColor.setText(_translate("Dialog", "Цвет текста в списке:"))
        self.label_4.setText(_translate("Dialog", "Стиль окна:"))
        self.pEdit.setPlainText(_translate("Dialog", "QWidget#centralwidget {\n"
"    background: #90202020;\n"
"    border-style: inset;\n"
"    border-width: 1px;\n"
"    border-color: #a0404050;\n"
"    border-radius: 10px;}\n"
"\n"
""))
        self.label_5.setText(_translate("Dialog", "Пример:"))
        self.bUpdate.setText(_translate("Dialog", "Обновить пример"))
        self.label_9.setText(_translate("Dialog", "Заголовок окна:"))
        self.bTitleColor.setText(_translate("Dialog", "Цвет заголовка окна"))
        self.bMenuBgColor.setText(_translate("Dialog", "Цвет фона меню"))
        self.bMenuColor.setText(_translate("Dialog", "Цвет текста меню"))
        self.bGroupTitleBorderColor.setText(_translate("Dialog", "Цвет рамки"))
        self.bGroupTitleBgColor.setText(_translate("Dialog", "Цвет фона"))
        self.bGroupTitleColor.setText(_translate("Dialog", "Цвет текста "))
        self.label_6.setText(_translate("Dialog", "Заголовок группы:"))
        self.bOk.setText(_translate("Dialog", "OK"))
        self.bCancel.setText(_translate("Dialog", "Отмена"))
